### ISSUE TITLE
[Bug] Connected Devices incorrect on RT-AC66U (Merlin) in AP mode

### ISSUE THREAD

**Issue by ejpenney** [Vaskivskyi/ha-asusrouter#465]
### The problem

Running in AP mode.

Answering your questions from the other thread:

1. _Do device tracker entities work? Or are they unavailable_
Every one of them is in the state "Away", even if the device is currently connected.

3. _By 0 connected devices you mean sensor.{device}\_connected\_devices value? What does sensor.{device}\_latest\_connected state?_
Yes, sensor.{device}_connected_devices state is "0".  sensor.{device}_latest_connected was disabled, I've enabled it and it is now in state "Unknown"

5. _Do other sensors work?_
I'm getting accurate data for CPU/RAM.  Upload/Download sensors are moving at rates that make sense given the activity on the AP.  The update sensor has the correct FW version reported.  No other entities are in state "Unknown", all the switches appear to work.

### Your device model

RT-AC66U

### Firmware type

Merlin

### Firmware version

3.0.0.4.380.70_0

### Integration version with the issue

0.17.4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.2

### Diagnostics information

[config_entry-asusrouter-15f1f46cae707323f7a986a2a95bac0d.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10385526/config_entry-asusrouter-15f1f46cae707323f7a986a2a95bac0d.json.txt)

**Comment by Vaskivskyi** [comment]
Hey, sorry for the late reply. Do you see the number of connected devices correctly in the Asus Web UI? Also, do you have errors in the log? I will try to reproduce the problem to find a solution, but that would require some time

**Comment by ejpenney** [comment]
Yes, I do. Thanks for the support.

![Screenshot_20230111-072523.png](https://user-images.githubusercontent.com/21226768/211845924-621f7147-df87-483b-a69f-df94bbe1ad8d.png)

**Comment by kuzhakhmetov** [comment]
I have the same isssue. RT-AC58U.
Everything is correct in the in web UI.

**Comment by kuzhakhmetov** [comment]
> @kuzhakhmetov, also in AP mode?

No, in Wireless router mode.

**Comment by sezlony** [comment]
same 0 devices connected bug here on RT-AC1200G+

**Comment by suxlala** [comment]
same, 0 devices connected, wireless mode, RT-AC85p
stock firmware: Fw: 3.0.0.4.382.52516_gcca929d 

Devices are found as device_tracker entities but with all data: null, and the connected devices sensor stays at 0

**Comment by Vaskivskyi** [comment]
Please, check whether the issue persists with the new version 0.18.0

**Comment by kuzhakhmetov** [comment]
> Please, check whether the issue persists with the new version 0.18.0
Working fine!
Thank you!

**Comment by suxlala** [comment]
> Please, check whether the issue persists with the new version 0.18.0

Works well now! Thanks a lot.

**Comment by ejpenney** [comment]
I can't connect at all in 0.18, but I suspect this is yet another bug:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/asusrouter/bridge.py:145
Integration: AsusRouter (documentation, issues)
First occurred: 8:43:03 AM (1 occurrences)
Last logged: 8:43:03 AM

Error setting up entry 192.168.86.34 for asusrouter
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 172, in async_request
    async with self._session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.86.34:8443 ssl:True [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 30, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 609, in setup
    await self.bridge.async_connect()
  File "/config/custom_components/asusrouter/bridge.py", line 145, in async_connect
    await self.api.async_connect()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 243, in async_connect
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 241, in async_connect
    await self.connection.async_connect()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 298, in async_connect
    response = await self.async_request(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 237, in async_request
    raise AsusRouterSSLError() from ex
asusrouter.error.AsusRouterSSLError: None

**Comment by Vaskivskyi** [comment]
@ejpenney,

Does your device use a self-signed certificate?

**Comment by ejpenney** [comment]
Yes

**Comment by Vaskivskyi** [comment]
Please, check whether there is still an SSL error in 0.18.1 (just released). If so, I will ask you for some additional tests with your device

**Comment by ejpenney** [comment]
New error:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/asusrouter/bridge.py:145
Integration: AsusRouter (documentation, issues)
First occurred: 10:11:15 AM (1 occurrences)
Last logged: 10:11:15 AM

Error setting up entry 192.168.86.34 for asusrouter
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 183, in async_request
    json_body = await reply.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
orjson.JSONDecodeError: byte order mark (BOM) is not supported: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 101, in async_run_command
    result = await self.async_request(command, endpoint, self._headers)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 231, in async_request
    json_body = parsers.pseudo_json(text=string_body, page=endpoint)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 434, in pseudo_json
    return endpoint_update_clients(text)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 423, in endpoint_update_clients
    return json.loads(data.encode().decode("utf-8-sig"))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 183, in async_request
    json_body = await reply.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
orjson.JSONDecodeError: byte order mark (BOM) is not supported: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 30, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 609, in setup
    await self.bridge.async_connect()
  File "/config/custom_components/asusrouter/bridge.py", line 145, in async_connect
    await self.api.async_connect()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 245, in async_connect
    await self.async_identify()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 338, in async_identify
    ] = await self.async_check_endpoint(address)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 232, in async_check_endpoint
    await self.async_api_load(endpoint)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 390, in async_api_load
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 383, in async_api_load
    result = await self.connection.async_run_command(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 113, in async_run_command
    return await self.async_run_command(command, endpoint, retry=True)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 114, in async_run_command
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 101, in async_run_command
    result = await self.async_request(command, endpoint, self._headers)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 231, in async_request
    json_body = parsers.pseudo_json(text=string_body, page=endpoint)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 434, in pseudo_json
    return endpoint_update_clients(text)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 423, in endpoint_update_clients
    return json.loads(data.encode().decode("utf-8-sig"))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 3)

**Comment by Vaskivskyi** [comment]
Could you please run this code from any environment with the `AsusRouter` library installed? If not installed yet (if used from outside of your HA environment), you can install it using `pip3 install asusrouter`

The code:
```python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
import asyncio


async def gather_data(host, username, password, use_ssl):
    """Method to gether all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, use_ssl = use_ssl)

    # Connect
    await router.connection.async_connect()

    # Get clients data in raw
    data = await router.connection.async_load("update_clients.asp")

    output = open("output.txt", "w", encoding="utf-8")
    output.write(data)

    # Disconnect
    await router.connection.async_disconnect()


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_use_ssl = True

loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))

loop.close()
```

You would need to create some `script.py` file and paste the code there. Just change the `_username`, `_password` and `_host` to your device credentials. Then you can run the script using `python3 script.py`.

When run, the script will create an `output.txt` file in the same folder with the raw content from the API endpoint that provides the errors you see in the log.

Please, send this file to me via email Yevhenii@Vaskivskyi.com. Please, don't publish the resulting file here as is - it will contain the MAC and IP addresses of your connected devices which you probably don't want to share. You will need to edit or remove them manually

**Comment by sezlony** [comment]
also this issue has been solved with 0.18.0 and still flawless on 0.18.1 for me 👌

**Comment by Vaskivskyi** [comment]
The issue is fixed in release 0.18.2. Please, check it

**Comment by ejpenney** [comment]
Didn't update clean. Caused startup to hang indefinitely and I had to remove and re-add the integration. Restarted a few times before things started looking better.

Device control switches are gone, but otherwise it's looking better...

**Comment by Vaskivskyi** [comment]
@ejpenney, please try to reboot your router and then restart the integration

Device control switches are available if the `Enable device control` option is true. You can change this option via the `Configure` button on the integrations page - Operation mode

After rebooting and checking that the setting is set correctly, please check the logs and let me know if there are any errors

**Comment by ejpenney** [comment]
Still missing.

Added this to my config:
```
logger:
  default: warning
  logs:
    custom_components.asusrouter: debug
    asusrouter: debug
```

Verified device control is enabled:
![image](https://user-images.githubusercontent.com/21226768/215345232-20ff144b-0b11-4694-8978-ff7dec0d091a.png)

I tried deleting the integration, rebooting.  Then re-adding.  Here's the complete log provided by asusrouter during setup.  No errors:
```
2023-01-29 09:35:24.210 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration asusrouter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-29 09:38:33.613 DEBUG (MainThread) [custom_components.asusrouter.config_flow] Setup initiated
2023-01-29 09:38:33.614 DEBUG (MainThread) [custom_components.asusrouter.bridge] Connecting to the API
2023-01-29 09:38:33.614 DEBUG (MainThread) [asusrouter.connection] Trying to connect
2023-01-29 09:38:33.614 DEBUG (MainThread) [asusrouter.connection] Sending connection request
2023-01-29 09:38:33.764 DEBUG (MainThread) [asusrouter.connection] Login successful on port `8443`: {'Model_Name': 'RT-AC66R', 'AiHOMEAPILevel': '6', 'Httpd_AiHome_Ver': '0'}
2023-01-29 09:38:33.764 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device
2023-01-29 09:38:37.127 DEBUG (MainThread) [asusrouter.asusrouter] Identity collected
2023-01-29 09:38:37.127 DEBUG (MainThread) [custom_components.asusrouter.bridge] Cleaning up
2023-01-29 09:38:37.127 DEBUG (MainThread) [asusrouter.connection] Cleaning up
2023-01-29 09:38:37.127 DEBUG (MainThread) [custom_components.asusrouter.bridge] Disconnecting from the API
2023-01-29 09:38:37.127 DEBUG (MainThread) [asusrouter.connection] Not connected
2023-01-29 09:38:37.127 DEBUG (MainThread) [asusrouter.connection] Cleaning up
2023-01-29 09:38:37.127 DEBUG (MainThread) [custom_components.asusrouter.config_flow] Setup successful
2023-01-29 09:38:45.239 DEBUG (MainThread) [custom_components.asusrouter.bridge] Connecting to the API
2023-01-29 09:38:45.239 DEBUG (MainThread) [asusrouter.connection] Trying to connect
2023-01-29 09:38:45.239 DEBUG (MainThread) [asusrouter.connection] Sending connection request
2023-01-29 09:38:45.390 DEBUG (MainThread) [asusrouter.connection] Login successful on port `8443`: {'Model_Name': 'RT-AC66R', 'AiHOMEAPILevel': '6', 'Httpd_AiHome_Ver': '0'}
2023-01-29 09:38:45.390 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device
2023-01-29 09:38:48.647 DEBUG (MainThread) [asusrouter.asusrouter] Identity collected
2023-01-29 09:38:48.647 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:38:48.647 DEBUG (MainThread) [asusrouter.asusrouter] Value `network` is not in cache yet by monitor `main` or the caching time has already expired
2023-01-29 09:38:48.647 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:38:48.802 DEBUG (MainThread) [asusrouter.asusrouter] Initializing constant `wlan`=`[]`
2023-01-29 09:38:48.802 DEBUG (MainThread) [custom_components.asusrouter.bridge] Disconnecting from the API
2023-01-29 09:38:48.946 DEBUG (MainThread) [asusrouter.connection] Cleaning up
2023-01-29 09:38:48.946 DEBUG (MainThread) [custom_components.asusrouter.config_flow] ['wan', 'wired', 'bridge', 'usb']
2023-01-29 09:39:05.682 DEBUG (MainThread) [custom_components.asusrouter] Setting up entry
2023-01-29 09:39:05.683 DEBUG (MainThread) [custom_components.asusrouter.router] Setting up router
2023-01-29 09:39:05.683 DEBUG (MainThread) [custom_components.asusrouter.bridge] Connecting to the API
2023-01-29 09:39:05.683 DEBUG (MainThread) [asusrouter.connection] Trying to connect
2023-01-29 09:39:05.683 DEBUG (MainThread) [asusrouter.connection] Sending connection request
2023-01-29 09:39:05.835 DEBUG (MainThread) [asusrouter.connection] Login successful on port `8443`: {'Model_Name': 'RT-AC66R', 'AiHOMEAPILevel': '6', 'Httpd_AiHome_Ver': '0'}
2023-01-29 09:39:05.835 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device
2023-01-29 09:39:09.527 DEBUG (MainThread) [asusrouter.asusrouter] Identity collected
2023-01-29 09:39:09.528 DEBUG (MainThread) [custom_components.asusrouter.router] Bridge connected
2023-01-29 09:39:09.530 DEBUG (MainThread) [custom_components.asusrouter.router] Updating AiMesh status for '192.168.86.34'
2023-01-29 09:39:09.531 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `onboarding` is disabled
2023-01-29 09:39:09.531 DEBUG (MainThread) [custom_components.asusrouter.router] Device tracking is enabled
2023-01-29 09:39:09.531 DEBUG (MainThread) [custom_components.asusrouter.router] Updating AsusRouter device list for '192.168.86.34'
2023-01-29 09:39:09.531 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `devices` is enabled
2023-01-29 09:39:09.531 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `onboarding` is disabled
2023-01-29 09:39:09.531 DEBUG (MainThread) [asusrouter.asusrouter] Value `clients` is not in cache yet by monitor `devices` or the caching time has already expired
2023-01-29 09:39:09.531 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `devices` is enabled
2023-01-29 09:39:09.718 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:09.718 DEBUG (MainThread) [asusrouter.asusrouter] Value `cpu` is not in cache yet by monitor `main` or the caching time has already expired
2023-01-29 09:39:09.718 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:09.873 DEBUG (MainThread) [asusrouter.asusrouter] Initializing constant `wlan`=`[]`
2023-01-29 09:39:09.873 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available `cpu` sensors: ['total_total', 'total_used', 'total_usage', '1_total', '1_used', '1_usage']
2023-01-29 09:39:09.873 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `nvram` is enabled
2023-01-29 09:39:09.873 DEBUG (MainThread) [asusrouter.asusrouter] Value `gwlan` is not in cache yet by monitor `nvram` or the caching time has already expired
2023-01-29 09:39:09.873 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `nvram` is enabled
2023-01-29 09:39:09.873 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `nvram` requires constant `wlan` to be found first. Initializing corresponding monitor
2023-01-29 09:39:09.873 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:10.027 DEBUG (MainThread) [asusrouter.asusrouter] Initializing constant `wlan`=`[]`
2023-01-29 09:39:10.028 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available `gwlan` sensors: {}
2023-01-29 09:39:10.028 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:10.028 DEBUG (MainThread) [asusrouter.asusrouter] Value `network` is already cached by monitor `main`. Using cache
2023-01-29 09:39:10.028 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available `network_stat` sensors: ['wan_rx', 'wan_rx_speed', 'wan_tx', 'wan_tx_speed', 'wired_rx', 'wired_rx_speed', 'wired_tx', 'wired_tx_speed', 'bridge_rx', 'bridge_rx_speed', 'bridge_tx', 'bridge_tx_speed', 'usb_rx', 'usb_rx_speed', 'usb_tx', 'usb_tx_speed']
2023-01-29 09:39:10.028 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `port_status` is disabled
2023-01-29 09:39:10.028 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `ethernet_ports` is enabled
2023-01-29 09:39:10.028 DEBUG (MainThread) [asusrouter.asusrouter] Value `ports` is not in cache yet by monitor `ethernet_ports` or the caching time has already expired
2023-01-29 09:39:10.028 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `ethernet_ports` is enabled
2023-01-29 09:39:10.207 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available `ports` sensors: ['lan_total', 'lan_1', 'lan_2', 'lan_3', 'lan_4', 'wan_total', 'wan_0']
2023-01-29 09:39:10.207 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `sysinfo` is enabled
2023-01-29 09:39:10.208 DEBUG (MainThread) [asusrouter.asusrouter] Value `sysinfo` is not in cache yet by monitor `sysinfo` or the caching time has already expired
2023-01-29 09:39:10.208 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `sysinfo` is enabled
2023-01-29 09:39:10.391 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available `sysinfo` sensors: ['load_avg_1', 'load_avg_5', 'load_avg_15']
2023-01-29 09:39:10.392 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `temperature` is enabled
2023-01-29 09:39:10.392 DEBUG (MainThread) [asusrouter.asusrouter] Value `temperature` is not in cache yet by monitor `temperature` or the caching time has already expired
2023-01-29 09:39:10.392 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `temperature` is enabled
2023-01-29 09:39:10.542 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available `temperature` sensors: {'5ghz': 58.0}
2023-01-29 09:39:10.542 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `devicemap` is enabled
2023-01-29 09:39:10.542 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `vpn` is enabled
2023-01-29 09:39:10.542 DEBUG (MainThread) [asusrouter.asusrouter] Value `vpn` is not in cache yet by monitor `devicemap` or the caching time has already expired
2023-01-29 09:39:10.542 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `devicemap` is enabled
2023-01-29 09:39:10.705 DEBUG (MainThread) [asusrouter.asusrouter] Value `vpn` is not in cache yet by monitor `vpn` or the caching time has already expired
2023-01-29 09:39:10.706 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `vpn` is enabled
2023-01-29 09:39:11.304 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available `vpn` sensors: ['vpn_client1_auth_read', 'vpn_client1_errno', 'vpn_client1_ip', 'vpn_client1_post_compress', 'vpn_client1_post_decompress', 'vpn_client1_pre_compress', 'vpn_client1_pre_decompress', 'vpn_client1_rip', 'vpn_client1_remote_auth', 'vpn_client1_remote_ip', 'vpn_client1_remote_port', 'vpn_client1_status', 'vpn_client1_tcp_udp_read', 'vpn_client1_tcp_udp_write', 'vpn_client1_tun_tap_read', 'vpn_client1_tun_tap_write', 'vpn_client1_datetime', 'vpn_client1_state', 'vpn_client2_auth_read', 'vpn_client2_errno', 'vpn_client2_ip', 'vpn_client2_post_compress', 'vpn_client2_post_decompress', 'vpn_client2_pre_compress', 'vpn_client2_pre_decompress', 'vpn_client2_rip', 'vpn_client2_remote_auth', 'vpn_client2_remote_ip', 'vpn_client2_remote_port', 'vpn_client2_status', 'vpn_client2_tcp_udp_read', 'vpn_client2_tcp_udp_write', 'vpn_client2_tun_tap_read', 'vpn_client2_tun_tap_write', 'vpn_client2_datetime', 'vpn_client2_state', 'vpn_client3_auth_read', 'vpn_client3_errno', 'vpn_client3_ip', 'vpn_client3_post_compress', 'vpn_client3_post_decompress', 'vpn_client3_pre_compress', 'vpn_client3_pre_decompress', 'vpn_client3_rip', 'vpn_client3_remote_auth', 'vpn_client3_remote_ip', 'vpn_client3_remote_port', 'vpn_client3_status', 'vpn_client3_tcp_udp_read', 'vpn_client3_tcp_udp_write', 'vpn_client3_tun_tap_read', 'vpn_client3_tun_tap_write', 'vpn_client3_datetime', 'vpn_client3_state', 'vpn_client4_auth_read', 'vpn_client4_errno', 'vpn_client4_ip', 'vpn_client4_post_compress', 'vpn_client4_post_decompress', 'vpn_client4_pre_compress', 'vpn_client4_pre_decompress', 'vpn_client4_rip', 'vpn_client4_remote_auth', 'vpn_client4_remote_ip', 'vpn_client4_remote_port', 'vpn_client4_status', 'vpn_client4_tcp_udp_read', 'vpn_client4_tcp_udp_write', 'vpn_client4_tun_tap_read', 'vpn_client4_tun_tap_write', 'vpn_client4_datetime', 'vpn_client4_state', 'vpn_client5_auth_read', 'vpn_client5_errno', 'vpn_client5_ip', 'vpn_client5_post_compress', 'vpn_client5_post_decompress', 'vpn_client5_pre_compress', 'vpn_client5_pre_decompress', 'vpn_client5_rip', 'vpn_client5_remote_auth', 'vpn_client5_remote_ip', 'vpn_client5_remote_port', 'vpn_client5_status', 'vpn_client5_tcp_udp_read', 'vpn_client5_tcp_udp_write', 'vpn_client5_tun_tap_read', 'vpn_client5_tun_tap_write', 'vpn_client5_datetime', 'vpn_client5_state', 'vpn_server1_client_list', 'vpn_server1_routing_table', 'vpn_server1_state', 'vpn_server2_client_list', 'vpn_server2_routing_table', 'vpn_server2_state']
2023-01-29 09:39:11.304 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `nvram` is enabled
2023-01-29 09:39:11.304 DEBUG (MainThread) [asusrouter.asusrouter] Value `wlan` is not in cache yet by monitor `nvram` or the caching time has already expired
2023-01-29 09:39:11.304 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `nvram` is enabled
2023-01-29 09:39:11.304 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `nvram` requires constant `wlan` to be found first. Initializing corresponding monitor
2023-01-29 09:39:11.305 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:11.462 DEBUG (MainThread) [asusrouter.asusrouter] Initializing constant `wlan`=`[]`
2023-01-29 09:39:11.462 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available `wlan` sensors: {}
2023-01-29 09:39:11.462 DEBUG (MainThread) [custom_components.asusrouter.bridge] Available sensors for mode=`access_point`: ['boottime', 'cpu', 'firmware', 'led', 'network', 'ports', 'ram', 'sysinfo', 'temperature', 'wlan']
2023-01-29 09:39:11.462 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `boottime`. Update interval: `0:00:30`
2023-01-29 09:39:11.462 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `devicemap` is enabled
2023-01-29 09:39:11.463 DEBUG (MainThread) [asusrouter.asusrouter] Value `boottime` is already cached by monitor `devicemap`. Using cache
2023-01-29 09:39:11.463 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching boottime data in 0.001 seconds (success: True)
2023-01-29 09:39:11.464 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `cpu`. Update interval: `0:00:30`
2023-01-29 09:39:11.464 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:11.464 DEBUG (MainThread) [asusrouter.asusrouter] Value `cpu` is already cached by monitor `main`. Using cache
2023-01-29 09:39:11.464 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching cpu data in 0.000 seconds (success: True)
2023-01-29 09:39:11.464 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `firmware`. Update interval: `6:00:00`
2023-01-29 09:39:11.464 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `firmware` is enabled
2023-01-29 09:39:11.464 DEBUG (MainThread) [asusrouter.asusrouter] Value `firmware` is not in cache yet by monitor `firmware` or the caching time has already expired
2023-01-29 09:39:11.464 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `firmware` is enabled
2023-01-29 09:39:11.619 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching firmware data in 0.154 seconds (success: True)
2023-01-29 09:39:11.619 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `led`. Update interval: `0:00:30`
2023-01-29 09:39:11.619 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `light` is enabled
2023-01-29 09:39:11.619 DEBUG (MainThread) [asusrouter.asusrouter] Value `led` is not in cache yet by monitor `light` or the caching time has already expired
2023-01-29 09:39:11.619 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `light` is enabled
2023-01-29 09:39:11.768 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching led data in 0.149 seconds (success: True)
2023-01-29 09:39:11.768 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `network`. Update interval: `0:00:30`
2023-01-29 09:39:11.768 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:11.768 DEBUG (MainThread) [asusrouter.asusrouter] Value `network` is already cached by monitor `main`. Using cache
2023-01-29 09:39:11.769 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching network data in 0.000 seconds (success: True)
2023-01-29 09:39:11.769 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `ports`. Update interval: `0:00:30`
2023-01-29 09:39:11.769 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `port_status` is disabled
2023-01-29 09:39:11.769 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `ethernet_ports` is enabled
2023-01-29 09:39:11.769 DEBUG (MainThread) [asusrouter.asusrouter] Value `ports` is already cached by monitor `ethernet_ports`. Using cache
2023-01-29 09:39:11.769 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching ports data in 0.000 seconds (success: True)
2023-01-29 09:39:11.769 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `ram`. Update interval: `0:00:30`
2023-01-29 09:39:11.769 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:11.769 DEBUG (MainThread) [asusrouter.asusrouter] Value `ram` is already cached by monitor `main`. Using cache
2023-01-29 09:39:11.769 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching ram data in 0.000 seconds (success: True)
2023-01-29 09:39:11.769 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `sysinfo`. Update interval: `0:00:30`
2023-01-29 09:39:11.770 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `sysinfo` is enabled
2023-01-29 09:39:11.770 DEBUG (MainThread) [asusrouter.asusrouter] Value `sysinfo` is already cached by monitor `sysinfo`. Using cache
2023-01-29 09:39:11.770 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching sysinfo data in 0.000 seconds (success: True)
2023-01-29 09:39:11.770 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `temperature`. Update interval: `0:00:30`
2023-01-29 09:39:11.770 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `temperature` is enabled
2023-01-29 09:39:11.770 DEBUG (MainThread) [asusrouter.asusrouter] Value `temperature` is already cached by monitor `temperature`. Using cache
2023-01-29 09:39:11.770 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching temperature data in 0.000 seconds (success: True)
2023-01-29 09:39:11.770 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `devices`. Update interval: `0:00:30`
2023-01-29 09:39:11.770 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching devices data in 0.000 seconds (success: True)
2023-01-29 09:39:11.770 DEBUG (MainThread) [custom_components.asusrouter.router] Coordinator initialized for `aimesh`. Update interval: `0:00:30`
2023-01-29 09:39:11.770 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching aimesh data in 0.000 seconds (success: True)
2023-01-29 09:39:11.789 DEBUG (MainThread) [custom_components.asusrouter.sensor] Interfaces selected: ['wan', 'wired']. Initializing sensors
2023-01-29 09:39:12.106 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `devicemap` is enabled
2023-01-29 09:39:12.106 DEBUG (MainThread) [asusrouter.asusrouter] Value `boottime` is already cached by monitor `devicemap`. Using cache
2023-01-29 09:39:12.106 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching boottime data in 0.000 seconds (success: True)
2023-01-29 09:39:12.106 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:12.106 DEBUG (MainThread) [asusrouter.asusrouter] Value `cpu` is already cached by monitor `main`. Using cache
2023-01-29 09:39:12.106 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching cpu data in 0.000 seconds (success: True)
2023-01-29 09:39:12.106 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:12.106 DEBUG (MainThread) [asusrouter.asusrouter] Value `network` is already cached by monitor `main`. Using cache
2023-01-29 09:39:12.106 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching network data in 0.000 seconds (success: True)
2023-01-29 09:39:12.115 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `port_status` is disabled
2023-01-29 09:39:12.115 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `ethernet_ports` is enabled
2023-01-29 09:39:12.116 DEBUG (MainThread) [asusrouter.asusrouter] Value `ports` is already cached by monitor `ethernet_ports`. Using cache
2023-01-29 09:39:12.116 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching ports data in 0.000 seconds (success: True)
2023-01-29 09:39:12.116 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `main` is enabled
2023-01-29 09:39:12.116 DEBUG (MainThread) [asusrouter.asusrouter] Value `ram` is already cached by monitor `main`. Using cache
2023-01-29 09:39:12.116 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching ram data in 0.000 seconds (success: True)
2023-01-29 09:39:12.116 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `sysinfo` is enabled
2023-01-29 09:39:12.117 DEBUG (MainThread) [asusrouter.asusrouter] Value `sysinfo` is already cached by monitor `sysinfo`. Using cache
2023-01-29 09:39:12.117 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching sysinfo data in 0.000 seconds (success: True)
2023-01-29 09:39:12.117 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `temperature` is enabled
2023-01-29 09:39:12.118 DEBUG (MainThread) [asusrouter.asusrouter] Value `temperature` is already cached by monitor `temperature`. Using cache
2023-01-29 09:39:12.118 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching temperature data in 0.000 seconds (success: True)
2023-01-29 09:39:12.118 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching devices data in 0.000 seconds (success: True)
2023-01-29 09:39:12.118 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching aimesh data in 0.000 seconds (success: True)
2023-01-29 09:39:12.118 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `firmware` is enabled
2023-01-29 09:39:12.118 DEBUG (MainThread) [asusrouter.asusrouter] Value `firmware` is already cached by monitor `firmware`. Using cache
2023-01-29 09:39:12.118 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching firmware data in 0.000 seconds (success: True)
```

**Comment by Vaskivskyi** [comment]
Ok. Strange...

So, no switches overall. But are there binary sensors instead of the switches that were before? Or just nothing?

**Comment by ejpenney** [comment]
Nothing.

![Screenshots_2023-01-29-10-24-41.png](https://user-images.githubusercontent.com/21226768/215348167-6b17ca5d-5b43-431a-b914-2dee1299caf6.png)

**Comment by ejpenney** [comment]
Looks like this started working in 0.20.

**Comment by ejpenney** [comment]
And device control stopped working in 0.21.1.  Not sure if it worked in 0.21.0, I skipped that version.

**Comment by Vaskivskyi** [comment]
Let's continue this discussion in issue #570. The problem with device trackers is happening for different users and it will be much easier to collect all the useful info in a single issue.
